version: '3.7'
services:
  # maknowledge:
  #   image: maknowledge:1.0
  #   ports:
  #     - 4000:4000
  #   restart: always
  postgres:
      image: postgres:14
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - 5432:5432
      volumes: 
        - ./postgres-data:/var/lib/postgresql/data