name: Snyk

on:
  push:
    branches:
      - 'master'
      - 'develop'
    paths:
    - 'server/**'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          entryPoint: ./server
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}