name: Unit Tests

on: 
  push:
    # run backend unit tests only when there are changes in server directory
    paths:
    - 'server/**'

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Get only backend files
        run: mv ./server/* ./

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm start
      # mocks need to be created, for now test only specific file
      - run: npm test examsController.test.js